A first pass at unit tests
They're very basic and still require a running local Instrumental (the Crapstrumental project) if you want to avoid seeing connection errors on your screen. The previous test script tested each of the various syntaxes available for each method. Maybe we want to do all those to. The previous script is still in the test directory, renamed 'old', and no longer runs by default with script/test.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -12,12 +12,13 @@ virtualenv --version > /dev/null  || (echo "virtualenv must be installed"; exit 
 for version in 2 3; do
   rm -rf venv-$version
   virtualenv --python="$(which "python$version")" "venv-$version"
+  pip install pytest
   source "venv-$version/bin/activate"
   pip install --upgrade ../
 
   # runs a test file with PASS/FAIL message
   run_test() {
-    python "$1" && echo "PASS $1 (Python $version)" || (echo "FAIL $1 (Python $version)"; exit 1)
+    py.test "$1" && echo "PASS $1 (Python $version)" || (echo "FAIL $1 (Python $version)"; exit 1)
   }
 
   if [ "$1" == "" ]; then
